server:
  port: 9100
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9761/eureka/
spring:
  redis:
    host: 127.0.0.1
    port: 6379
uca:
  oauth2:
    client:
      id: backstage
      secret: back$tage$ecret
      token-url: http://bs-zuul-server/bs-auth-server/oauth/token
      web:
        name: webclient
        timeout: 3600 # 1 hour
      mobile:
        name: mobileclient
        timeout: 604800 # 1 week