server:
  port: 9100
spring:
  redis:
    host: 127.0.0.1
    port: 6379
uca:
  oauth2:
    client:
      id: backstage
      secret: back$tage$ecret
      web-scope: webclient
      mobile-scope: mobileclient
      login-url: http://bs-zuul-server/bs-auth-server/oauth/token