spring:
  redis:
    host: 192.168.63.195
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.63.195:9761/eureka/
logging:
  config: http://192.168.63.195:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 192.168.63.195:4567