server:
  port: 8130
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/plat_file?allowMultiQueries=true
    username: andy
    password: password
  redis:
    host: 127.0.0.1
    port: 6379
  resources:
    static-locations: file:${uca.plat.file.exposed-location}
  jooq:
    sql-dialect: mysql
logging:
  config: http://127.0.0.1:8888/fs-logback/default/master/logback-spring.xml
  level:
    org:
      jooq: debug
logstash:
  destination: 127.0.0.1:4567
uca:
  plat:
    file:
      url: http://127.0.0.1:8555/fs-plat-file
      real-file-path: ${uca.plat.file.exposed-location}/media
      exposed-location: /opt/uca/file
security:
  oauth2:
    resource:
      user-info-uri: http://fs-zuul-server/fs-auth-server/user
    client:
      grant-type: client_credentials