server:
  port: 9110
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/platform_sys
    username: andy
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jooq:
    sql-dialect: mysql
logging:
  config: http://127.0.0.1:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 127.0.0.1:4567
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:9901/user
    client:
      grant-type: client_credentials