eureka:
  client:
    service-url:
      defaultZone: http://192.168.63.195:9761/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/plat_file?allowMultiQueries=true
    username: uca
    password: password
  redis:
    host: 192.168.63.195
    port: 6379
  resources:
    static-locations: file:${uca.plat.file.exposed-location}
uca:
  plat:
    file:
      # 统一以前台的入口来对附件进行下载
      url: http://192.168.63.195:8555/fs-plat-file
      real-file-path: ${uca.plat.file.exposed-location}/media
      exposed-location: /opt/uca/file
logging:
  config: http://192.168.63.195:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 192.168.63.195:4567