server:
  port: 8120
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/corporate
    username: andy
    password: password
  jooq:
    sql-dialect: mysql
logging:
  config: http://127.0.0.1:8888/fs-logback/default/master/logback-spring.xml
  level:
    org:
      jooq: debug
logstash:
  destination: 127.0.0.1:4567

security:
  oauth2:
    resource:
      user-info-uri: http://fs-zuul-server/fs-auth-server/user
    client:
      grant-type: client_credentials