server:
  port: 7901
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.63.195:8761/eureka/
spring:
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/bs_auth
    username: uca
    password: password
  cloud:
    stream:
      bindings:
        input-change-phone:
          group: input-change-phone
          destination: bs-auth-change-phone
          content-type: application/json
        input-change-email:
          group: input-change-email
          destination: bs-auth-change-email
          content-type: application/json
  rabbitmq:
    host: 192.168.63.195
    port: 5672
    username: guest
    password: guest
logging:
  level:
    org:
      hibernate: debug
auth-server:
  client-id: bs-portal
  client-secret: bs-portal$ecret
  grant-types:
    - refresh_token
    - password
    - client_credential
  scopes:
    - webclient
    - mobileclient