server:
  port: 9901
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.63.195:9761/eureka/
spring:
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/bs_auth
    username: uca
    password: password
  rabbitmq:
    host: 192.168.63.195
    port: 5672
    username: guest
    password: guest
logging:
  config: http://192.168.63.195:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 192.168.63.195:4567