server:
  port: 8901
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.63.195:8761/eureka/
spring:
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/fs_auth
    username: uca
    password: password
  rabbitmq:
    host: 192.168.63.195
    port: 5672
    username: guest
    password: guest
logstash:
  destination: 192.168.63.195:4567