spring:
  redis:
    host: 192.168.63.195
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.63.195:8761/eureka/
logging:
  config: http://192.168.63.195:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 192.168.63.195:4567