spring:
  redis:
    host: 192.168.63.195
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.63.195:8761/eureka/
uca:
  oauth2:
    client:
      token-url: http://192.168.63.195:8555/fs-auth-server/oauth/token